// AUTO-GENERATED FILE. DO NOT EDIT.
// This file is generated by generate-registry-map.js to bundle component sources for Vercel Serverless Functions.
export const componentSourceMap: Record<string, string> = {};
